<a href="https://colab.research.google.com/github/Hassanashraf20/E-SHOP/blob/main/Copy_of_Information_Retrieval_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import the necessary libraries
import nltk
import string
import re

from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords, wordnet
from nltk import pos_tag
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

# Make sure to download necessary NLTK data
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')



documents = [
    "She sells seashells by the seashore.",
    "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
    "To be or not to be, that is the question.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Roses are red, violets are blue, sugar is sweet, and so are you.",
    "The cat in the hat sat on the mat.",
    "All that glitters is not gold.",
    "It was the best of times, it was the worst of times.",
    "In a hole in the ground, there lived a hobbit.",
    "To be or not to be, that is the question.",
    "The quick brown fox jumps over the lazy dog.",
    "She sells seashells by the seashore.",
    "How much wood would a woodchuck ?",
    "Hey, did you know that the summer break is coming? Amazing right!! It's only 5 more days!!",
    "There are 3 balls in this bag, and 12 in the other one.",
    "To be or not to be, that is the question.",
    "The quick brown fox jumps over the lazy dog.",
    "She sells seashells by the seashore.",
    "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
    "To be or not to be, that is the question.",
    "we don't need   the given questions",
    "This is a sample sentence and we are going to remove the stopwords from this.",
    "data science uses scientific methods algorithms and many types of processes",
    "n this article, we will learn by using various Python Libraries and Techniques that are involved in Text Processing.",
    "There are 66 bell in this bag, and 33 in the other one.",
    " Gettysburg Address by Abraham Lincoln",
    " Declaration of Independence by Thomas Jefferson",
    " Emancipation Proclamation by Abraham Lincoln",
    "The Magna Carta ",
    "The Bill of Rights "
    "The Emancipation Proclamation ",
    "The Gettysburg Address ",
    " Emancipation Proclamation ",
    "The 19th Amendment ",
    "The Social Security Act ",
    "The Civil Rights Act ",
    "The Voting Rights Act ",
    "The Fair Housing Act ",
    " Americans with Disabilities Act ",
    "The Affordable Care Act ",
    " Dodd-Frank Wall Street Reform and Consumer Protection Act ",
    "The Tax Cuts and Jobs Act"
]

query = ["She sells seashells by the seashore"]

# Preprocessing
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# Function to convert NLTK's part of speech tags to wordnet tags
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN  # Default to noun if unknown

def preprocess(document):
    words = nltk.word_tokenize(document.lower())
    pos_tags = pos_tag(words)
    filtered_words = [
        lemmatizer.lemmatize(word, get_wordnet_pos(pos))
        for word, pos in pos_tags
        if word not in stop_words and word.isalnum()
    ]
    return filtered_words

preprocessed_docs = [preprocess(doc) for doc in docs]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:

#Preprocessing
# Text preprocessing functions
def text_lowercase(text):
    return text.lower()

def remove_numbers(text):
    result = re.sub(r'\d+', '', text)
    return result

def remove_punctuation(text):
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

# Apply preprocessing to each document
preprocessed_documents = []
for doc in documents:
    doc = text_lowercase(doc)
    doc = remove_numbers(doc)
    doc = remove_punctuation(doc)
    preprocessed_documents.append(doc)

print(preprocessed_documents)


['she sells seashells by the seashore', 'how much wood would a woodchuck chuck if a woodchuck could chuck wood', 'to be or not to be that is the question', 'lorem ipsum dolor sit amet consectetur adipiscing elit', 'roses are red violets are blue sugar is sweet and so are you', 'the cat in the hat sat on the mat', 'all that glitters is not gold', 'it was the best of times it was the worst of times', 'in a hole in the ground there lived a hobbit', 'to be or not to be that is the question', 'the quick brown fox jumps over the lazy dog', 'she sells seashells by the seashore', 'how much wood would a woodchuck ', 'hey did you know that the summer break is coming amazing right its only  more days', 'there are  balls in this bag and  in the other one', 'to be or not to be that is the question', 'the quick brown fox jumps over the lazy dog', 'she sells seashells by the seashore', 'how much wood would a woodchuck chuck if a woodchuck could chuck wood', 'to be or not to be that is the question', 

In [ ]:
# Lemmatization
lemmatizer = WordNetLemmatizer()
lemmatized_tokens = [lemmatizer.lemmatize(word) for word in preprocessed_documents]
print(lemmatized_tokens)



['she sells seashells by the seashore', 'how much wood would a woodchuck chuck if a woodchuck could chuck wood', 'to be or not to be that is the question', 'lorem ipsum dolor sit amet consectetur adipiscing elit', 'roses are red violets are blue sugar is sweet and so are you', 'the cat in the hat sat on the mat', 'all that glitters is not gold', 'it was the best of times it was the worst of times', 'in a hole in the ground there lived a hobbit', 'to be or not to be that is the question', 'the quick brown fox jumps over the lazy dog', 'she sells seashells by the seashore', 'how much wood would a woodchuck ', 'hey did you know that the summer break is coming amazing right its only  more days', 'there are  balls in this bag and  in the other one', 'to be or not to be that is the question', 'the quick brown fox jumps over the lazy dog', 'she sells seashells by the seashore', 'how much wood would a woodchuck chuck if a woodchuck could chuck wood', 'to be or not to be that is the question', 

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Create the CountVectorizer object
vectorizer = CountVectorizer()

# Fit the vectorizer to the documents
term_matrix = vectorizer.fit_transform(preprocessed_documents)

# Get the terms (features)
terms = vectorizer.get_feature_names_out()

# Print the term matrix
print(term_matrix.todense())
print("\n")
print("Terms:\n", terms)






[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Terms:
 ['abraham' 'act' 'address' 'adipiscing' 'affordable' 'algorithms' 'all'
 'amazing' 'amendment' 'americans' 'amet' 'and' 'are' 'article' 'bag'
 'balls' 'be' 'bell' 'best' 'bill' 'blue' 'break' 'brown' 'by' 'care'
 'carta' 'cat' 'chuck' 'civil' 'coming' 'consectetur' 'consumer' 'could'
 'cuts' 'data' 'days' 'declaration' 'did' 'disabilities' 'doddfrank' 'dog'
 'dolor' 'dont' 'elit' 'emancipation' 'fair' 'fox' 'from' 'gettysburg'
 'given' 'glitters' 'going' 'gold' 'ground' 'hat' 'hey' 'hobbit' 'hole'
 'housing' 'how' 'if' 'in' 'independence' 'involved' 'ipsum' 'is' 'it'
 'its' 'jefferson' 'jobs' 'jumps' 'know' 'lazy' 'learn' 'libraries'
 'lincoln' 'lived' 'lorem' 'magna' 'many' 'mat' 'methods' 'more' 'much'
 'need' 'not' 'of' 'on' 'one' 'only' 'or' 'other' 'over' 'processes'
 'processing' 'proclamation' 'protection' 'python' 'question' 'questions'
 'quick' 'red

In [ ]:
term_incidence_matrix = term_matrix.todense()
print(term_incidence_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [ ]:
def boolean_query(query, operation):
    query_terms = preprocess(query)
    # Initialize the query vector to match the term incidence matrix's dimensions
    query_vector = np.zeros(term_incidence_matrix.shape[0], dtype=int)

    for term in query_terms:
        if term in terms:
            term_index = terms.index(term)
            query_vector[term_index] = 1  # Mark term as present


    # Apply Boolean operations using bitwise operations on the matrix
    if operation == "AND":
        # For 'AND', all terms in the query must be present in a document
        result_mask = np.prod(term_incidence_matrix[query_vector == 1, :], axis=0) == 1
    elif operation == "OR":
        # For 'OR', any of the terms can be present
        result_mask = np.sum(term_incidence_matrix[query_vector == 1, :], axis=0) > 0
    elif operation == "NOT":
        # 'NOT' is more complex and often used with other conditions. This example assumes you want documents without the terms.
        result_mask = np.sum(term_incidence_matrix[query_vector == 1, :], axis=0) == 0
    else:
        raise ValueError("Unknown operation")

    # Convert mask to boolean array to select matching documents
    return result_mask.astype(bool)

In [ ]:
# Execute an example query
query = "sells"
operation = "AND"
result = boolean_query(query, operation)

# Output matching documents
print("Documents matching the query:")
for i, match in enumerate(result):
    if match.all():
        print(f"Document {i} : {preprocessed_documents[i]} " )

Documents matching the query:
Document 0 : she sells seashells by the seashore 


In [ ]:
# Execute an example query
query = "shore"
operation = "NOT"
result = boolean_query(query, operation)

# Output matching documents
print("Documents matching the query:")
for i, match in enumerate(result):
    if match.all():
        print(f"Document {i} : {preprocessed_documents[i]} " )

Documents matching the query:
Document 0 : she sells seashells by the seashore 


In [ ]:
# Adjusted preprocessing function to handle list input for documents and query
def preprocess_documents(documents):
    preprocessed_docs = []
    for doc in documents:
        # Remove punctuation and convert to lowercase
        doc_no_punctuation = doc.translate(str.maketrans('', '', string.punctuation)).lower()
        # Lemmatize the document
        tokens = doc_no_punctuation.split()
        lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
        preprocessed_docs.append(' '.join(lemmatized_tokens))
    return preprocessed_docs

In [ ]:
# Preprocess the documents and the query
preprocessed_documents = preprocess_documents(preprocessed_documents)
#preprocessed_query = preprocess_documents(query)

In [ ]:
preprocessed_documents

['she sell seashell by the seashore',
 'how much wood would a woodchuck chuck if a woodchuck could chuck wood',
 'to be or not to be that is the question',
 'lorem ipsum dolor sit amet consectetur adipiscing elit',
 'rose are red violet are blue sugar is sweet and so are you',
 'the cat in the hat sat on the mat',
 'all that glitter is not gold',
 'it wa the best of time it wa the worst of time',
 'in a hole in the ground there lived a hobbit',
 'to be or not to be that is the question',
 'the quick brown fox jump over the lazy dog',
 'she sell seashell by the seashore',
 'how much wood would a woodchuck',
 'hey did you know that the summer break is coming amazing right it only more day',
 'there are ball in this bag and in the other one',
 'to be or not to be that is the question',
 'the quick brown fox jump over the lazy dog',
 'she sell seashell by the seashore',
 'how much wood would a woodchuck chuck if a woodchuck could chuck wood',
 'to be or not to be that is the question',
 'w

In [ ]:
# Compute the cosine similarity of the query to the documents
cosine_sim = cosine_similarity(tfidf_matrix[-1], tfidf_matrix[:-1])

In [ ]:
print(cosine_sim )

[[0.03362208 0.         0.02277647 0.         0.05456155 0.07122086
  0.         0.02973195 0.02319943 0.02277647 0.04925204 0.03362208
  0.         0.01646525 0.09282639 0.02277647 0.04925204 0.03362208
  0.         0.02277647 0.02785309 0.07839427 0.06311954 0.0522114
  0.09282639 0.         0.         0.         0.04193549 0.06002057
  0.0462989  0.         0.04193549 0.16431563 0.17561996 0.17561996
  0.16431563 0.10829698 0.16431563 0.15315506]]


In [ ]:
# Rank documents based on their cosine similarity to the query
sorted_indices = np.argsort(cosine_sim[0])[::-1]
ranked_documents = {f"Document {index+1}": cosine_sim[0][index] for index in sorted_indices}

ranked_documents

{'Document 36': 0.17561996220870263,
 'Document 35': 0.17561996220870263,
 'Document 37': 0.1643156288199158,
 'Document 34': 0.1643156288199158,
 'Document 39': 0.1643156288199158,
 'Document 40': 0.15315506445764465,
 'Document 38': 0.10829698465106331,
 'Document 25': 0.09282639294761394,
 'Document 15': 0.09282639294761394,
 'Document 22': 0.07839427424529716,
 'Document 6': 0.0712208598155101,
 'Document 23': 0.06311953663419147,
 'Document 30': 0.06002057453625364,
 'Document 5': 0.05456155355649612,
 'Document 24': 0.05221140402628178,
 'Document 17': 0.049252036974424825,
 'Document 11': 0.049252036974424825,
 'Document 31': 0.04629889705033121,
 'Document 33': 0.041935492658273794,
 'Document 29': 0.041935492658273794,
 'Document 12': 0.03362208175014476,
 'Document 18': 0.03362208175014476,
 'Document 1': 0.03362208175014476,
 'Document 8': 0.02973194771786725,
 'Document 21': 0.02785308804944127,
 'Document 9': 0.02319942872360029,
 'Document 10': 0.02277646639333377,
 'Docu